# syntax=docker/dockerfile:1.4
# Multi-stage build for Next.js on Cloud Run
# Optimized for production deployment with BuildKit caching

# Stage 1: Dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install ALL dependencies with BuildKit cache mount for npm
RUN --mount=type=cache,target=/root/.npm \
    npm ci && \
    npm cache clean --force

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy all source files
COPY . .

# Set environment variables for build
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Accept build arguments for Next.js public environment variables
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_INTELIMOTOR_BUSINESS_UNIT_ID
ARG NEXT_PUBLIC_INTELIMOTOR_API_KEY
ARG NEXT_PUBLIC_INTELIMOTOR_API_SECRET
ARG NEXT_PUBLIC_AIRTABLE_VALUATION_API_KEY
ARG NEXT_PUBLIC_AIRTABLE_VALUATION_BASE_ID
ARG NEXT_PUBLIC_AIRTABLE_VALUATION_TABLE_ID
ARG NEXT_PUBLIC_AIRTABLE_VALUATION_VIEW
ARG NEXT_PUBLIC_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID
ARG NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_API_KEY
ARG NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_BASE_ID
ARG NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_TABLE_ID
ARG NEXT_PUBLIC_IMAGE_CDN_URL
ARG NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_URL
ARG NEXT_PUBLIC_CLOUDFLARE_ACCOUNT_ID
ARG NEXT_PUBLIC_CLOUDFLARE_R2_ACCESS_KEY_ID
ARG NEXT_PUBLIC_CLOUDFLARE_R2_SECRET_ACCESS_KEY
ARG NEXT_PUBLIC_CAR_STUDIO_API_KEY
ARG NEXT_PUBLIC_LEAD_CONNECTOR_WEBHOOK_URL
ARG NEXT_PUBLIC_LANDING_WEBHOOK_URL
ARG NEXT_PUBLIC_APPLICATION_WEBHOOK_URL
ARG NEXT_PUBLIC_PROXY_URL
ARG NEXT_PUBLIC_CALENDLY_URL_MTY
ARG NEXT_PUBLIC_CALENDLY_URL_TMPS
ARG NEXT_PUBLIC_CALENDLY_URL_COAH
ARG NEXT_PUBLIC_CALENDLY_URL_GPE
ARG NEXT_PUBLIC_FRONTEND_URL
ARG NEXT_PUBLIC_CLOUD_RUN_URL
ARG NEXT_PUBLIC_GIT_COMMIT
ARG NEXT_PUBLIC_BUILD_DATE
ARG NEXT_PUBLIC_ENVIRONMENT

# Set them as environment variables for the build
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_INTELIMOTOR_BUSINESS_UNIT_ID=$NEXT_PUBLIC_INTELIMOTOR_BUSINESS_UNIT_ID
ENV NEXT_PUBLIC_INTELIMOTOR_API_KEY=$NEXT_PUBLIC_INTELIMOTOR_API_KEY
ENV NEXT_PUBLIC_INTELIMOTOR_API_SECRET=$NEXT_PUBLIC_INTELIMOTOR_API_SECRET
ENV NEXT_PUBLIC_AIRTABLE_VALUATION_API_KEY=$NEXT_PUBLIC_AIRTABLE_VALUATION_API_KEY
ENV NEXT_PUBLIC_AIRTABLE_VALUATION_BASE_ID=$NEXT_PUBLIC_AIRTABLE_VALUATION_BASE_ID
ENV NEXT_PUBLIC_AIRTABLE_VALUATION_TABLE_ID=$NEXT_PUBLIC_AIRTABLE_VALUATION_TABLE_ID
ENV NEXT_PUBLIC_AIRTABLE_VALUATION_VIEW=$NEXT_PUBLIC_AIRTABLE_VALUATION_VIEW
ENV NEXT_PUBLIC_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID=$NEXT_PUBLIC_AIRTABLE_VALUATIONS_STORAGE_TABLE_ID
ENV NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_API_KEY=$NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_API_KEY
ENV NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_BASE_ID=$NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_BASE_ID
ENV NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_TABLE_ID=$NEXT_PUBLIC_AIRTABLE_LEAD_CAPTURE_TABLE_ID
ENV NEXT_PUBLIC_IMAGE_CDN_URL=$NEXT_PUBLIC_IMAGE_CDN_URL
ENV NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_URL=$NEXT_PUBLIC_CLOUDFLARE_R2_PUBLIC_URL
ENV NEXT_PUBLIC_CLOUDFLARE_ACCOUNT_ID=$NEXT_PUBLIC_CLOUDFLARE_ACCOUNT_ID
ENV NEXT_PUBLIC_CLOUDFLARE_R2_ACCESS_KEY_ID=$NEXT_PUBLIC_CLOUDFLARE_R2_ACCESS_KEY_ID
ENV NEXT_PUBLIC_CLOUDFLARE_R2_SECRET_ACCESS_KEY=$NEXT_PUBLIC_CLOUDFLARE_R2_SECRET_ACCESS_KEY
ENV NEXT_PUBLIC_CAR_STUDIO_API_KEY=$NEXT_PUBLIC_CAR_STUDIO_API_KEY
ENV NEXT_PUBLIC_LEAD_CONNECTOR_WEBHOOK_URL=$NEXT_PUBLIC_LEAD_CONNECTOR_WEBHOOK_URL
ENV NEXT_PUBLIC_LANDING_WEBHOOK_URL=$NEXT_PUBLIC_LANDING_WEBHOOK_URL
ENV NEXT_PUBLIC_APPLICATION_WEBHOOK_URL=$NEXT_PUBLIC_APPLICATION_WEBHOOK_URL
ENV NEXT_PUBLIC_PROXY_URL=$NEXT_PUBLIC_PROXY_URL
ENV NEXT_PUBLIC_CALENDLY_URL_MTY=$NEXT_PUBLIC_CALENDLY_URL_MTY
ENV NEXT_PUBLIC_CALENDLY_URL_TMPS=$NEXT_PUBLIC_CALENDLY_URL_TMPS
ENV NEXT_PUBLIC_CALENDLY_URL_COAH=$NEXT_PUBLIC_CALENDLY_URL_COAH
ENV NEXT_PUBLIC_CALENDLY_URL_GPE=$NEXT_PUBLIC_CALENDLY_URL_GPE
ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL
ENV NEXT_PUBLIC_CLOUD_RUN_URL=$NEXT_PUBLIC_CLOUD_RUN_URL
ENV NEXT_PUBLIC_GIT_COMMIT=$NEXT_PUBLIC_GIT_COMMIT
ENV NEXT_PUBLIC_BUILD_DATE=$NEXT_PUBLIC_BUILD_DATE
ENV NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT

# Build Next.js application with BuildKit cache for Next.js cache
RUN --mount=type=cache,target=/app/.next/cache \
    npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Set correct permissions
RUN chown -R nextjs:nodejs /app

# Switch to non-root user
USER nextjs

# Expose port
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "require('http').get('http://localhost:8080/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"

# Start the application
CMD ["node", "server.js"]
